ALPHABET_LOG = {',': 'AAA', '(': 'AAC', 'a': 'AAT', 'b': 'AAG', 'c': 'ACA', 'd': 'ACC', 'e': 'ACT', 'f': 'ACG', 'g': 'ATA', 'h': 'ATC', 'i': 'ATT', 'j': 'ATG', 'k': 'AGA', 'l': 'AGC', 'm': 'AGT', 'n': 'AGG', 'o': 'CAA', 'p': 'CAC', 'q': 'CAT', 'r': 'CAG', 's': 'CCA', 't': 'CCC', 'u': 'CCT', 'v': 'CCG', 'w': 'CTA', 'x': 'CTC', 'y': 'CTT', 'z': 'CTG', '0': 'CGA', '1': 'CGC', '2': 'CGT', '3': 'CGG', '4': 'TAA', '5': 'TAC', '6': 'TAT', '7': 'TAG', '8': 'TCA', '9': 'TCC'}
INVERSE_ALPHABET_LOG = {'AAA': ',', 'AAC': '(', 'AAT': 'a', 'AAG': 'b', 'ACA': 'c', 'ACC': 'd', 'ACT': 'e', 'ACG': 'f', 'ATA': 'g', 'ATC': 'h', 'ATT': 'i', 'ATG': 'j', 'AGA': 'k', 'AGC': 'l', 'AGT': 'm', 'AGG': 'n', 'CAA': 'o', 'CAC': 'p', 'CAT': 'q', 'CAG': 'r', 'CCA': 's', 'CCC': 't', 'CCT': 'u', 'CCG': 'v', 'CTA': 'w', 'CTC': 'x', 'CTT': 'y', 'CTG': 'z', 'CGA': '0', 'CGC': '1', 'CGT': '2', 'CGG': '3', 'TAA': '4', 'TAC': '5', 'TAT': '6', 'TAG': '7', 'TCA': '8', 'TCC': '9'}

ALPHABET_BRACKET = {',': 'A', '(': 'AA', 'a': 'CCCC', 'b': 'CCCT', 'c': 'CCCG', 'd': 'CCTC', 'e': 'CCTT', 'f': 'CCTG', 'g': 'CCGC', 'h': 'CCGT', 'i': 'CCGG', 'j': 'CTCC', 'k': 'CTCT', 'l': 'CTCG', 'm': 'CTTC', 'n': 'CTTT', 'o': 'CTTG', 'p': 'CTGC', 'q': 'CTGT', 'r': 'CTGG', 's': 'CGCC', 't': 'CGCT', 'u': 'CGCG', 'v': 'CGTC', 'w': 'CGTT', 'x': 'CGTG', 'y': 'CGGC', 'z': 'CGGT', '0': 'CGGG', '1': 'TCCC', '2': 'TCCT', '3': 'TCCG', '4': 'TCTC', '5': 'TCTT', '6': 'TCTG', '7': 'TCGC', '8': 'TCGT', '9': 'TCGG'}
INVERSE_ALPHABET_BRACKET = {'A': ',', 'AA': '(', 'CCCC': 'a', 'CCCT': 'b', 'CCCG': 'c', 'CCTC': 'd', 'CCTT': 'e', 'CCTG': 'f', 'CCGC': 'g', 'CCGT': 'h', 'CCGG': 'i', 'CTCC': 'j', 'CTCT': 'k', 'CTCG': 'l', 'CTTC': 'm', 'CTTT': 'n', 'CTTG': 'o', 'CTGC': 'p', 'CTGT': 'q', 'CTGG': 'r', 'CGCC': 's', 'CGCT': 't', 'CGCG': 'u', 'CGTC': 'v', 'CGTT': 'w', 'CGTG': 'x', 'CGGC': 'y', 'CGGT': 'z', 'CGGG': '0', 'TCCC': '1', 'TCCT': '2', 'TCCG': '3', 'TCTC': '4', 'TCTT': '5', 'TCTG': '6', 'TCGC': '7', 'TCGT': '8', 'TCGG': '9'}

ALPHABET_BRACKET_IMPROVED = {',': 'G', '(': 'GG', 'a': 'AAA', 'b': 'AAC', 'c': 'AAT', 'd': 'AAG', 'e': 'ACA', 'f': 'ACC', 'g': 'ACT', 'h': 'ACG', 'i': 'ATA', 'j': 'ATC', 'k': 'ATT', 'l': 'ATG', 'm': 'AGA', 'n': 'AGC', 'o': 'AGT', 'p': 'AGG', 'q': 'CAA', 'r': 'CAC', 's': 'CAT', 't': 'CAG', 'u': 'CCA', 'v': 'CCC', 'w': 'CCT', 'x': 'CCG', 'y': 'CTA', 'z': 'CTC', '0': 'CTT', '1': 'CTG', '2': 'CGA', '3': 'CGC', '4': 'CGT', '5': 'CGG', '6': 'TAA', '7': 'TAC', '8': 'TAT', '9': 'TAG'}
INVERSE_ALPHABET_BRACKET_IMPROVED = {'G': ',', 'GG': '(', 'AAA': 'a', 'AAC': 'b', 'AAT': 'c', 'AAG': 'd', 'ACA': 'e', 'ACC': 'f', 'ACT': 'g', 'ACG': 'h', 'ATA': 'i', 'ATC': 'j', 'ATT': 'k', 'ATG': 'l', 'AGA': 'm', 'AGC': 'n', 'AGT': 'o', 'AGG': 'p', 'CAA': 'q', 'CAC': 'r', 'CAT': 's', 'CAG': 't', 'CCA': 'u', 'CCC': 'v', 'CCT': 'w', 'CCG': 'x', 'CTA': 'y', 'CTC': 'z', 'CTT': '0', 'CTG': '1', 'CGA': '2', 'CGC': '3', 'CGT': '4', 'CGG': '5', 'TAA': '6', 'TAC': '7', 'TAT': '8', 'TAG': '9'}

ALPHABET_BRACKET_IMPROVED2 = {'(': 'G', ',': 'T', 'a': 'AAAA', 'b': 'AAAC', 'c': 'AAAT', 'd': 'AAAG', 'e': 'AACA', 'f': 'AACC', 'g': 'AACT', 'h': 'AACG', 'i': 'AATA', 'j': 'AATC', 'k': 'AATT', 'l': 'AATG', 'm': 'AAGA', 'n': 'AAGC', 'o': 'AAGT', 'p': 'AAGG', 'q': 'ACAA', 'r': 'ACAC', 's': 'ACAT', 't': 'ACAG', 'u': 'ACCA', 'v': 'ACCC', 'w': 'ACCT', 'x': 'ACCG', 'y': 'ACTA', 'z': 'ACTC', '0': 'ACTT', '1': 'ACTG', '2': 'ACGA', '3': 'ACGC', '4': 'ACGT', '5': 'ACGG', '6': 'ATAA', '7': 'ATAC', '8': 'ATAT', '9': 'ATAG'}
INVERSE_ALPHABET_BRACKET_IMPROVED2 = {'G': '(', 'T': ',', 'AAAA': 'a', 'AAAC': 'b', 'AAAT': 'c', 'AAAG': 'd', 'AACA': 'e', 'AACC': 'f', 'AACT': 'g', 'AACG': 'h', 'AATA': 'i', 'AATC': 'j', 'AATT': 'k', 'AATG': 'l', 'AAGA': 'm', 'AAGC': 'n', 'AAGT': 'o', 'AAGG': 'p', 'ACAA': 'q', 'ACAC': 'r', 'ACAT': 's', 'ACAG': 't', 'ACCA': 'u', 'ACCC': 'v', 'ACCT': 'w', 'ACCG': 'x', 'ACTA': 'y', 'ACTC': 'z', 'ACTT': '0', 'ACTG': '1', 'ACGA': '2', 'ACGC': '3', 'ACGT': '4', 'ACGG': '5', 'ATAA': '6', 'ATAC': '7', 'ATAT': '8', 'ATAG': '9'}
